[IMP] theme_paptic: update the theme
odoo/design-themes pull request #467
Opened 2021-07-30 06:45 UTC by Brieuc-brd

Update the theme to improve the design with shapes, new pictures and new custom snippets.

**Improvements :**
- Update the tour : add Comparisons and Call_to_action
- Cover : change color preset to improve the color of buttons
- Image_text : add more space before the arrow of the button
- Three_columns : improve the layout of cards and keep the original card structure
- Update the screenshot
- Picture : change the shape color for a better contrast with the title.

**New customisations :**
- Comparisons
- Call_to_action
- Banner
- Numbers
- Big Boxes (Color_blocks_2)
- Features
- Masonry
- Media_list
- Features_grid
- Pricelist

Task-2602618

2021-07-30 06:46 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/design-themes/pull/467).

2021-08-06 09:00 UTC, qsm-odoo requested changes
I just flied over the PR, nothing too scary I think :+1: (obviously the less custo I see, the better I'll sleep but... :laughing:)

Make sure to take care of my comments (for all of your snippets and other themes too, and share the comments with the other designers :+1: )

Note: commit message:
- This commit update**s**
- Max 72 characters per line in the description but use those 72 characters (not 50 like you did)

Courage ! :)

2021-09-16 09:45 UTC, qsm-odoo requested changes
@Brieuc-brd This seems good :+1: I only have two useless comments to make, if you can handle them and make sure no other change is needed, I'll then test and merge this one today :+1:

Note: I already rebased on 14.5, push-forced and retargeted the PR.

Could you also adapt (if needed) the related IAP PR and mention it in the paptic task? So we can merge them together. Thanks :+1:

2021-09-16 09:45 UTC, qsm-odoo commented on theme_paptic/data/ir_asset.xml
> +    </record>
When you reindent, reindent following our convention, no indentation and blank line around:

```xml
<odoo>

<record>
[...]
</record>

</odoo>
```

2021-09-16 09:45 UTC, qsm-odoo commented on theme_paptic/static/src/js/tour.js
> +import wTourUtils from 'website.tour_utils';
I know I am annoying but if you can add a blank line after `/** @odoo-module */`... thanks :+1:

2021-09-16 10:44 UTC, Brieuc-brd commented
Hello @qsm-odoo 👋 
I made the changes you asked and added the link of the IAP PR in the paptic task. 👍 
I also add it here : [https://github.com/odoo/iap-apps/pull/404](url)

2021-09-16 13:13 UTC, qsm-odoo approved these changes
@robodoo r+

2021-09-16 13:17 UTC, qsm-odoo commented
@robodoo r-

2021-09-16 14:25 UTC, qsm-odoo commented
@robodoo r+

2021-09-16 16:17 UTC, closed without merging