[IMP] theme_kiddo, theme_vehicule: add images_peview_theme in manifest
odoo/design-themes pull request #482
Opened 2021-08-09 16:51 UTC by JKE-be

@robodoo r+

Example of how to communicate image to be used by IAP in preview when use_theme_image is checked on iap.
//cc @Cocographique

2021-08-09 16:52 UTC, JKE-be commented
@robodoo r+

//cc @Cocographique

2021-08-09 16:52 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/design-themes/pull/482).

2021-08-09 17:00 UTC, robodoo commented
Linked pull request(s) odoo/odoo#74887 not ready. Linked PRs are not staged until all of them are ready.

2021-08-09 17:19 UTC, qsm-odoo requested changes

2021-08-09 17:19 UTC, qsm-odoo commented on theme_kiddo/__manifest__.py
> +    'images_peview_theme': {
"peview" ? :wink:

2021-08-09 18:28 UTC, JKE-be commented
@qsm-odoo thank you ;) 
don't hesitate to r- when you are sure that it is wrong ;) 
I don't bite and I'm able to see that I'm wrong when it is the case (most of the time :p) ;)

2021-08-10 14:33 UTC, rdeodoo commented on theme_vehicle/__manifest__.py
> +    'images_peview_theme': {
:eye:

2021-08-10 14:36 UTC, rdeodoo commented on theme_vehicle/__manifest__.py
> +    'images_peview_theme': {
fixed this one
 I guess it can be  r+ now?

2021-08-16 07:20 UTC, JKE-be commented
@robodoo r+

2021-08-16 09:23 UTC, closed without merging