[IMP] test_themes: (re)add preview to website (themes) switcher.
odoo/design-themes pull request #573
Opened 2022-06-29 15:45 UTC by detrouxdev

Commit [1] moved the website switcher from the frontend to the backend
and in doing so re-factored it into an OWL component.

Initially, this refactoring broke the theme preview from the previous
widget. This commit re-introduces those previews.

[1]:

2022-06-29 15:46 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/design-themes/pull/573).

2022-07-05 14:37 UTC, detrouxdev commented
@rdeodoo Not that much of a priority but I think I'd be neat to have it back 😄

2022-07-08 16:53 UTC, rdeodoo requested changes

2022-07-08 16:58 UTC, rdeodoo approved these changes
@robodoo r+ thank :+1: 

I applied the changed myself here https://github.com/odoo/design-themes/compare/b3bc433d2b774330b246e87dba03cbde38a8714c..417cf6dfad8513a251cb38d5e1c2173c5670146e

Note that the comment left in the code during the FE>BE merge was to keep the history. Thus a move commit could have been a good thing but we actually really don't care bout those files which are fully rewritten anyway.

The JS part could probably be improved a bit now that we return a simpler dict but this is LGTM

2022-07-08 17:24 UTC, rdeodoo commented
@robodoo r+

2022-07-08 19:01 UTC, closed without merging