[FIX] website_animate: fix animations rotate in down
odoo/design-themes pull request #6
Opened 2021-05-28 07:05 UTC by bvr-odoo

These animations did not launch correctly because we were trying to
get the position of the element (by not taking CSS transforms into
calculations) via the matrix of the css transform and it doesnt work
if there is a transform-origin on the element.

Now we find the top position by checking that of its parent.

task-2215118

2021-05-28 07:05 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/design-themes/pull/6).

2021-06-08 14:51 UTC, qsm-odoo requested changes
How can I reproduce the bug you are fixing here?

2021-06-08 14:51 UTC, qsm-odoo commented on website_animate/static/src/js/o_animate.frontend.js
> +        // and add it's parent's offset to get page offset
- "its"
- Break line at 80 characters (not 30)

2021-06-08 14:51 UTC, qsm-odoo commented on website_animate/static/src/js/o_animate.frontend.js
> +        let element = el;
Don't use `let` in 12.0

2021-06-14 07:21 UTC, bvr-odoo commented
> How can I reproduce the bug you are fixing here?

The animations "Rotate In-Down-Left" and "Rotate In-Down-Right" doesnt work without this fix.

2021-06-14 10:29 UTC, qsm-odoo commented
> > How can I reproduce the bug you are fixing here?
> 
> The animations "Rotate In-Down-Left" and "Rotate In-Down-Right" doesnt work without this fix.

I would not ask that question if that was that simple to reproduce... :/ I just retested in 12.0 on both Chrome and Firefox and there is no problem on my side :grimacing: I can't see the difference with or without your fix, so please give me more info :wink:

2021-06-14 15:02 UTC, bvr-odoo commented
> > > How can I reproduce the bug you are fixing here?
> > 
> > 
> > The animations "Rotate In-Down-Left" and "Rotate In-Down-Right" doesnt work without this fix.
> 
> I would not ask that question if that was that simple to reproduce... :/ I just retested in 12.0 on both Chrome and Firefox and there is no problem on my side  I can't see the difference with or without your fix, so please give me more info

I'm sorry but I don't really have more info to give you :)
I have the issue in V12 in Chrome and in Firefox

1 - drop a snippet text-image
2 - add Rotate In-Down-Left animation on this snippet
3 - save the page
4 - the animation is not started

2021-07-26 10:49 UTC, qsm-odoo approved these changes
@robodoo r+

2021-07-26 12:15 UTC, closed without merging