[IMP] theme_*: remove default shapes on demand
odoo/design-themes pull request #692
Opened 2023-08-21 14:30 UTC by bso-odoo

This commit removes the default shapes that are added on blocks by the themes in order to avoid having wrongly joined shapes when creating new pages from templates.

An `ignore_shape` context value is set to `True` if the default shapes need to be skipped.

task-3381714

2023-08-21 15:43 UTC, qsm-odoo requested changes
@bso-odoo Let's talk about this tomorrow, live with @rdeodoo. Would be nice to have feedback of your meeting with the designers :)

For this `ignore_shape` stuff, I am not sure about the need. And if there is one, I don't think it should be about tweaking the definition of all theme overrides.

2023-10-12 15:11 UTC, bso-odoo commented
@rdeodoo Ouch... I just noticed the `new_page_templates.xml` for `theme_beauty` was not in the manifest... (it became obvious when merging the commits) So... I added it, it does not crash... but I think we will have to review the templates for that theme.

If we prefer, I can restore the previous display - by removing the customizations form that file. Sorry for not noticing earlier.

2023-10-13 16:35 UTC, rdeodoo commented
@robodoo rebase-ff

2023-10-13 16:36 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2023-10-13 21:06 UTC, rdeodoo approved these changes
@robodoo r+ rebase-ff

Impressive work, good job to all people related to those theme customization and Benoit for cleaning / adapting.
I wasn't expecting that deep customization / pixel perfect usage of the new page templates, and I am honestly not 100% fan of going that far but as it's 100% done according to the spec, it was the way to go.
Note that when I say not a fan, I mean it in a way that the technical debt is big here.
But since the added value is also awesome for our end users, I guess the `technical debt` / `added value` ratio is fine.

2023-10-13 21:06 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2023-10-14 04:31 UTC, closed without merging