[REM] theme_*: remove useless scss variable overrides
odoo/design-themes pull request #768
Opened 2024-02-13 11:57 UTC by Guillaume-gdi

This commit removes the overrides of scss variables that are set to the default value.

task-2463604

2024-02-13 11:57 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/design-themes/pull/768).

2024-03-07 16:58 UTC, rdeodoo commented
@robodoo delegate=@xO-Tx

2024-03-14 09:01 UTC, xO-Tx requested changes
@Guillaume-gdi small tweaks before r+ :+1:

MYSCR(`x`) => Maybe You Should Consider Removing `x` :wink:.

2024-03-14 15:00 UTC, Guillaume-gdi commented
Thank your for the great review @xO-Tx! I adapted the PR :heavy_check_mark:

2024-03-15 15:21 UTC, xO-Tx commented
@Guillaume-gdi thanks for the update (and for removing the other overrides of `menu-box-shadow`...) :+1:
@robodoo r+

2024-03-15 17:15 UTC, closed without merging