[DRAFT][IMP] adapt snippet design
odoo/design-themes pull request #823
Opened 2024-07-12 12:02 UTC by chgo-odoo

2024-07-12 12:03 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/design-themes/pull/823.png)](https://mergebot.odoo.com/odoo/design-themes/pull/823)

2024-07-16 10:02 UTC, stefanorigano approved these changes
Great, LGTM, thanks @chgo-odoo 👍
.. waiting for linked PRs...

2024-07-30 09:57 UTC, sobo-odoo commented
@robodoo delegate=bvr-odoo

2024-07-30 12:51 UTC, bvr-odoo requested changes
A small change needed, otherwise all good. Thanks.

2024-07-30 12:51 UTC, bvr-odoo commented on theme_vehicle/views/customizations.xml
> +        <attribute name="class" add="o_cc5 pt96" remove="o_cc5 pt64" separator=" "/>
no need to remove then add `o_cc5` :wink:

2024-07-30 14:52 UTC, chgo-odoo commented
Thanks @bvr-odoo, changes done, should be good, normally, could you have a look, please?

2024-07-30 16:58 UTC, closed without merging