[DRAFT][IMP] Master website cover banner textcover anso
odoo/design-themes pull request #827
Opened 2024-07-15 12:59 UTC by chgo-odoo

2024-07-15 13:00 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/design-themes/pull/827.png)](https://mergebot.odoo.com/odoo/design-themes/pull/827)

2024-07-24 08:52 UTC, stefanorigano requested changes
Good @chgo-odoo , some remarks for you, courage 💪 

edit: @chgo-odoo , don't forget commits and PRs titles/descriptions

2024-07-24 08:52 UTC, stefanorigano commented on theme_enark/views/snippets/s_cover.xml
> -<template id="s_cover" inherit_id="website.s_cover">
Let's not remove templates for now unless really necessary.
We'll have to review each theme, chances are that we'll have to re-create the very same template but applying other customizations ;)
Replace the xpath with something that makes sense for this theme... adjust the padding maybe?

2024-07-24 08:52 UTC, stefanorigano commented on theme_anelusia/views/snippets/s_text_cover.xml
>  <template id="s_text_cover" inherit_id="website.s_text_cover">
Looks broken
![image](https://github.com/user-attachments/assets/ffbcd962-f81e-41bd-b23a-a70abc0787da)

2024-07-24 08:52 UTC, stefanorigano commented on theme_beauty/views/snippets/s_cover.xml
> +        <attribute name="class" add="o_full_screen_height bg-black-15 o_cc o_cc5" remove="bg-black-50 o_cc o_cc4" separator=" "/>
You're both adding and removing the `o_cc` class ... lucky the adding operation is processed after the removal, so the class it's there, but let's fix that ;)

```suggestion
        <attribute name="class" add="o_full_screen_height bg-black-15 o_cc5" remove="bg-black-50 o_cc4" separator=" "/>
```

2024-07-24 08:52 UTC, stefanorigano commented on theme_buzzy/views/new_page_template.xml
> -<template id="new_page_template_about_s_text_cover" inherit_id="website.new_page_template_about_s_text_cover">
Here again, let's not remove templates for now.
Replace the xpath with something that makes sense for this snippet.

2024-07-24 08:52 UTC, stefanorigano commented on theme_enark/__manifest__.py
> -        'views/snippets/s_cover.xml',
Chances are that we'll have to add it back, for now let's not remove the file ;)

2024-07-24 08:52 UTC, stefanorigano commented on theme_graphene/views/customizations.xml
>  <template id="s_cover" inherit_id="website.s_cover" name="Graphene s_cover">
Text is not readable

![image](https://github.com/user-attachments/assets/d65c22f5-8dce-4ab4-9b42-a7f1b488d937)

2024-07-24 08:52 UTC, stefanorigano commented on theme_kiddo/views/snippets/s_cover.xml
> +        <attribute name="class" add="o_full_screen_height o_cc1" remove="bg-black-50 o_cc4" separator=" "/>
Buttons are not very visible

| this pr | master |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/71d2be73-3c06-4bdf-ba84-02a033b7b8ea) | ![image](https://github.com/user-attachments/assets/70b539c1-3dd6-40ea-bbda-ea86996103fb) |

2024-07-24 08:52 UTC, stefanorigano commented on theme_loftspace/views/snippets/s_cover.xml
> +        <attribute name="class" add="o_full_screen_height" separator=" "/>
Unreadable text

![image](https://github.com/user-attachments/assets/eff2d5e5-13c9-42f0-84e7-32570434035f)

2024-07-24 08:52 UTC, stefanorigano commented on theme_monglia/views/customizations.xml
>   <template id="s_cover" inherit_id="website.s_cover" name="Monglia s_cover">
Primary buttons work better here ;)

| this PR | master |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/f46c9fbe-97ef-4da4-b101-0d44322ecef2) | ![image](https://github.com/user-attachments/assets/616a5320-ee1a-45a0-91aa-63ed527ee2b4) |

2024-07-24 16:12 UTC, chgo-odoo commented
@stefanorigano changes done, could you check please ?

2024-07-24 16:31 UTC, stefanorigano approved these changes
LGTM, well done 💪

2024-07-26 15:31 UTC, bso-odoo commented
@robodoo rebase-ff r+

2024-07-26 15:32 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2024-07-26 18:55 UTC, closed without merging