[IMP] test_themes, theme_buzzy: s_form adaptations
odoo/design-themes pull request #832
Opened 2024-07-16 13:15 UTC by Brieuc-brd

This commit adapts the s_form customizations since this snippet has been redesigned in PR [1].

task-4048101

[1]: https://github.com/odoo/odoo/pull/172763

Requires: 
- https://github.com/odoo/odoo/pull/172763

2024-07-16 13:16 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/design-themes/pull/832.png)](https://mergebot.odoo.com/odoo/design-themes/pull/832)

2024-07-18 15:49 UTC, stefanorigano requested changes
Thanks @Brieuc-brd  👍

2024-07-18 15:49 UTC, stefanorigano commented on theme_buzzy/views/new_page_template.xml
> -
Let's not remove templates for now ;)

2024-07-18 15:49 UTC, stefanorigano commented on test_themes/tests/test_new_page_templates.py
> +        's_website_form_custom', 's_website_form_dnone', 's_website_form_field', 's_website_form_input', 's_website_form_mark', 's_website_form_submit', 's_website_form_no_submit_label',
Not sure about this... makes sense to me but I'll leave it for the tech. review 😉

2024-07-18 18:35 UTC, Brieuc-brd commented
@stefanorigano 👋 
Branch updated, what do you think ?

2024-07-18 18:41 UTC, stefanorigano approved these changes
LGTM, thanks 👍

2024-07-24 11:49 UTC, sobo-odoo commented
@robodoo delegate=robinlej

2024-07-25 07:49 UTC, robinlej commented
@robodoo r+

2024-07-25 09:33 UTC, closed without merging