[IMP] test_anelusia, *: s_color_blocks_2 adaptations
odoo/design-themes pull request #834
Opened 2024-07-17 13:49 UTC by Brieuc-brd

*: theme_artists, theme_beauty, theme_bewise, theme_buzzy, theme_clean, theme_cobalt, theme_kea, theme_loftspace, theme_notes, theme_odoo_experts, theme_paptic, theme_treehouse, theme_zap

This commit adapts the s_color_blocks_2 customizations since this snippet has been redesigned in PR[1].

task-3619705

[1]: https://github.com/odoo/odoo/pull/173461

Requires: 
- https://github.com/odoo/odoo/pull/173461

2024-07-17 13:49 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/design-themes/pull/834.png)](https://mergebot.odoo.com/odoo/design-themes/pull/834)

2024-07-17 19:21 UTC, stefanorigano approved these changes
LGTM, thanks 👍

2024-07-26 09:58 UTC, sobo-odoo requested changes
Everything looks fine :slightly_smiling_face: 
I just have a comment on the commit message (see review comment) :+1:

2024-07-26 11:44 UTC, Brieuc-brd commented on theme_anelusia/views/snippets/s_color_blocks_2.xml
>  <template id="s_color_blocks_2" inherit_id="website.s_color_blocks_2">
Done ✅ 😉

2024-07-26 15:44 UTC, sobo-odoo approved these changes
@robodoo r+

2024-07-26 18:55 UTC, closed without merging