[IMP] theme_buzzy: s_timeline adaptations
odoo/design-themes pull request #845
Opened 2024-07-25 15:33 UTC by Brieuc-brd

This commit adapts the s_timeline customizations since this snippet has been redesigned in PR[1].

task-3657763
Part of task-3619705

Requires:
- https://github.com/odoo/odoo/pull/172720

[1]: https://github.com/odoo/odoo/pull/172720

2024-07-25 15:34 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/design-themes/pull/845.png)](https://mergebot.odoo.com/odoo/design-themes/pull/845)

2024-07-25 21:38 UTC, stefanorigano approved these changes
All good, thanks 👍

2024-07-26 18:52 UTC, sobo-odoo requested changes
Here is a small commit message review :wink:

2024-07-26 18:52 UTC, sobo-odoo commented on theme_buzzy/views/new_page_template.xml
>  </template>
Commit message:
- the commit message should start with a verb :wink: => adapt s_timeline
- nitpick: space between PR et [1] :slightly_smiling_face:

2024-08-05 14:31 UTC, sobo-odoo approved these changes
@robodoo r+

2024-08-05 16:56 UTC, closed without merging