[IMP] theme_*: adapt themes with new `s_sidegrid` snippet
odoo/design-themes pull request #853
Opened 2024-08-03 16:35 UTC by anso-odoo

*: (artists, bookstore, enark, graphene, loftspace, notes, real_estate, vehicle, zap)

This commit adapts the design of new `s_sidegrid` snippet for multiple themes.

task-4077589

requires:

2024-08-03 16:36 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/design-themes/pull/853.png)](https://mergebot.odoo.com/odoo/design-themes/pull/853)

2024-08-06 08:55 UTC, stefanorigano requested changes
I think that we should do a bit more to ensure that the snippet matches themes.
I find the "building" and the "3" pictures a bit problematic when it comes to themes like "Yes" or "Kiddo" or "Anelusia".  Demo text should be replaced as well. 
![image](https://github.com/user-attachments/assets/54702a23-c49a-4cbc-82b8-fc62ce03907a)

2024-08-06 10:46 UTC, anso-odoo commented
@stefanorigano done ✅

2024-08-06 14:59 UTC, stefanorigano approved these changes
LGTM, thanks @anso-odoo 👍

2024-09-03 11:54 UTC, SergeBayet approved these changes
LGTM. Thanks :)

2024-09-04 09:25 UTC, bso-odoo commented
@robodoo delegate=SergeBayet

2024-09-06 15:14 UTC, closed without merging