[IMP] theme_*: adapt themes with new `s_unveil` snippet
odoo/design-themes pull request #860
Opened 2024-08-08 15:38 UTC by xlu-odoo

*: anelusia, avantgarde, aviato, beauty, bewise, bookstore, ernark, graphene, kea, kiddo, loftspace, monglia, nano, notes, odoo experts, orchid, paptic, real_estate, treehouse, vehicle, yes, zap

This commit adapts the design of new s_unveil snippet for multiple themes.

task-4104471
part-of: task-4077427

requires: https://github.com/odoo/odoo/pull/176167

2024-08-08 15:39 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/design-themes/pull/860.png)](https://mergebot.odoo.com/odoo/design-themes/pull/860)

2024-08-09 07:56 UTC, anso-odoo approved these changes
Good job 👏

2024-08-09 07:56 UTC, anso-odoo commented on theme_beauty/views/snippets/s_unveil.xml
> +        Unleash Your Beauty
Not sure about this one 😂 otherwise LGTM !

2024-08-12 18:56 UTC, sobo-odoo requested changes
Here is my review :slightly_smiling_face:

2024-08-12 18:56 UTC, sobo-odoo commented on theme_clean/views/snippets/s_unveil.xml
> +<?xml version="1.0" encoding="utf-8"?>
You forgot to add this one in the manifest :wink:

2024-08-13 10:57 UTC, sobo-odoo commented
@xlu-odoo (just in case you didn't see, I posted my review for design-themes :arrow_up: :wink: )

2024-08-13 11:05 UTC, xlu-odoo commented
> @xlu-odoo (just in case you didn't see, I posted my review for design-themes ⬆️ 😉 )

Yes, I did see it and thought that I pushed my changes.  😶‍🌫️

2024-08-13 13:10 UTC, sobo-odoo approved these changes
@robodoo r+

2024-08-14 11:07 UTC, closed without merging