[IMP] theme_bookstore: theme improvement
odoo/design-themes pull request #862
Opened 2024-08-12 12:38 UTC by anso-odoo

Revamp of `theme_bookstore`

task-4109584

2024-08-12 12:39 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/design-themes/pull/862.png)](https://mergebot.odoo.com/odoo/design-themes/pull/862)

2024-08-14 10:43 UTC, stefanorigano approved these changes
Some mirrors to address, could be done during the tech. review 👍 
LGTM @anso-odoo , good job.

2024-08-14 10:43 UTC, stefanorigano commented on theme_bookstore/views/snippets/s_banner.xml
> +            <a href="/shop" class="btn btn-lg btn-primary"><i class="fa fa-shopping-cart me-2"/> Shop Now <span class="fa fa-angle-right ms-2"/></a>
`role="img"`

2024-08-14 10:43 UTC, stefanorigano commented on theme_bookstore/views/snippets/s_banner.xml
> +            <a t-att-href="cta_btn_href" class="btn btn-lg btn-primary">Start Now <span class="fa fa-angle-right ms-2"/></a>
`role="img"`

2024-08-14 15:16 UTC, sobo-odoo requested changes
Here is my review :slightly_smiling_face:

2024-08-14 15:16 UTC, sobo-odoo commented on theme_bookstore/views/snippets/s_showcase.xml
> +        Prime quality second-hand books, carefully selected for value and charm— timeless stories at great prices.
Is the "charm-" made like "I was about to say charming but i preferred to say timeless instead" or is there a typo ?

2024-08-14 15:16 UTC, sobo-odoo commented on theme_bookstore/views/snippets/s_title.xml
> +        <div class="o_we_shape o_web_editor_Airy_03_001 o_we_animated" style="background-image: url('/web_editor/shape/web_editor%2FAiry%2F03_001.svg?c5=%23FC5B02');"/>
There is no need in encoding with the `%2F` normally :slightly_smiling_face:

2024-08-14 15:16 UTC, sobo-odoo commented on theme_bookstore/views/snippets/s_cta_box.xml
> +        </t>
Same comment about making a db request :grimacing:

2024-08-14 15:47 UTC, anso-odoo commented
Thanks ! @sobo-odoo Everything should be fine now 👍

2024-08-14 17:21 UTC, sobo-odoo commented
@anso-odoo @stefanorigano I [force pushed](https://github.com/odoo/design-themes/compare/f6ccaef44267a5df70ef8c8091e55d680f7cadce..2f29f8e422ab61d5894a44bec805e00a195c4bdd) to:
- replace the forced orange color of the "Title" shape by `o-color-1`
- remove the configurator versions of the "Call to action" and the "Image Text" snippets, since they are not dropped by the configurator anymore (there was a crash because of call to action) :+1: 
- remove the last step of the tour, since there is no `snippet[5]` anymore :+1:

2024-08-14 18:35 UTC, sobo-odoo approved these changes
@robodoo r+

2024-08-15 07:15 UTC, closed without merging