[IMP] theme_*: review s_empowerment occurrences
odoo/design-themes pull request #875
Opened 2024-08-19 17:37 UTC by chgo-odoo

*: anelusia, artists, avantgarde, aviato, beauty, bewise, bistro, bookstore, buzzy, clean, cobalt, enark, graphene, kea, kiddo, loftspace, monglia, nano, notes, odoo_experts, orchid, paptic, real_estate, treehouse, vehicle, yes, zap

task-4094396
Part of task-4077427

2024-08-19 17:38 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/design-themes/pull/875.png)](https://mergebot.odoo.com/odoo/design-themes/pull/875)

2024-08-22 12:04 UTC, xlu-odoo requested changes
Aside from those two comments, content looks great! 🚀

2024-08-27 13:27 UTC, xlu-odoo approved these changes
LGTM! 🚀

2024-09-02 15:26 UTC, bso-odoo reviewed
Is it intentional that zap has no customization ?

2024-09-02 15:26 UTC, bso-odoo commented on theme_avantgarde/static/src/img/.DS_Store
It seems a `.DS_Store` file made its way into the repo.

2024-09-20 14:12 UTC, bvr-odoo approved these changes

2024-09-20 14:31 UTC, bvr-odoo commented
Commit(s) moved into

- https://github.com/odoo/design-themes/pull/919

2024-09-20 16:53 UTC, closed without merging