[IMP] theme_*: adapt `s_connections` snippet
odoo/design-themes pull request #876
Opened 2024-08-21 09:48 UTC by chgo-odoo

This commit reviews the occurrences of `s_connections` snippet across design themes.

task-4077616
part of task-4077427

2024-09-11 09:00 UTC, anso-odoo commented on theme_aviato/views/images_library.xml
> +<record id="website.s_split_intro_default_image" model="ir.attachment">
I think there is a small careless mistake here and in `theme_beauty`. You are overwriting the default record 👍

2024-09-11 09:01 UTC, anso-odoo commented on theme_avantgarde/static/src/img/pictures/s_split_intro_default_image.jpg
`theme_avantgarde` is missing a new image record

2024-09-11 15:43 UTC, anso-odoo requested changes
Hey @chgo-odoo, some record urls need to be fixed 👍

2024-09-11 15:43 UTC, anso-odoo commented on theme_avantgarde/views/images_library.xml
>  </odoo>
Missing empty line

2024-09-11 15:43 UTC, anso-odoo commented on theme_avantgarde/views/images_library.xml
> +    <field name="url">/theme_avantgarde/static/src/img/snippets_demo/s_split_intro_default_image.jpg</field>
```suggestion
    <field name="url">/theme_avantgarde/static/src/img/pictures/s_split_intro_default_image.jpg</field>
```

2024-09-11 15:43 UTC, anso-odoo commented on theme_beauty/views/images.xml
> +    <field name="url">/theme_beauty/static/src/img/content/s_split_intro_default_image.jpg</field>
```suggestion
    <field name="url">/theme_beauty/static/src/img/snippets/s_split_intro_default_image.jpg</field>
```

2025-02-14 14:17 UTC, chrisdt1998 approved these changes
All the pictures are noticeably low resolution. Is it possible to increase all the resolution sizes?

Otherwise LGTM :)

2025-02-17 08:24 UTC, chgo-odoo commented
Hello @chrisdt1998 👋 

I rebased both branches and fixed the conflicts

2025-02-17 08:27 UTC, chrisdt1998 commented
Hello @chgo-odoo . Ok great, I will r+ as soon as the tests pass.

2025-02-17 10:48 UTC, chrisdt1998 commented
@robodoo r+

2025-02-17 13:22 UTC, closed without merging