[IMP] theme_*: adapt themes with new `s_card_offset` design
odoo/design-themes pull request #877
Opened 2024-08-21 15:26 UTC by xlu-odoo

*: anelusia, artists, avantgarde, aviato, beauty, bewise, bistro, bookstore, buzzy, clean, cobalt, enark, graphene, kea, kiddo, loftspace, monglia, nano, notes, odoo_experts, orchid, paptic, real estate, treehouse, vehicle, yes, zap

This commit adapts the design of `s_card_offset` for multiple themes, based on the new Odoo 18 snippet redesign.

task-4105038
Part-of: task-4077427

2024-08-21 15:27 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/design-themes/pull/877.png)](https://mergebot.odoo.com/odoo/design-themes/pull/877)

2024-08-27 12:44 UTC, Brieuc-brd requested changes
Thanks @xlu-odoo 👍 
I just found a color issue applied on some themes, could you check ?

2024-08-27 12:44 UTC, Brieuc-brd commented on theme_bistro/views/snippets/s_card_offset.xml
> +        <attribute name="class" add="o_cc5" remove="o_cc1" separator=" "/>
```suggestion
        <attribute name="class" add="o_cc5 o_colored_level" remove="o_cc1" separator=" "/>
```
Little color issue : 
![Capture d’écran 2024-08-27 à 14 37 09](https://github.com/user-attachments/assets/e7fc1971-d9dd-4a4a-a152-1f7d62d3f980)

2024-08-27 12:44 UTC, Brieuc-brd commented on theme_enark/views/snippets/s_card_offset.xml
> +        <attribute name="class" add="o_cc5" remove="o_cc1" separator=" "/>
```suggestion
        <attribute name="class" add="o_cc5 o_colored_level" remove="o_cc1" separator=" "/>
```
Color issue :
![Capture d’écran 2024-08-27 à 14 39 24](https://github.com/user-attachments/assets/d8667eb1-c93d-43ee-b4f5-0ec42f9c8518)

2024-08-27 12:44 UTC, Brieuc-brd commented on theme_nano/views/snippets/s_card_offset.xml
> +        <attribute name="class" add="o_cc5" remove="o_cc1" separator=" "/>
```suggestion
        <attribute name="class" add="o_cc5 o_colored_level" remove="o_cc1" separator=" "/>
```
Color issue :
![Capture d’écran 2024-08-27 à 14 41 28](https://github.com/user-attachments/assets/cb9bc607-e9bb-404d-a490-18f9ea7588c7)

2024-08-27 12:44 UTC, Brieuc-brd commented on theme_yes/views/snippets/s_card_offset.xml
> +        <attribute name="class" add="o_cc5" remove="o_cc1" separator=" "/>
```suggestion
        <attribute name="class" add="o_cc5 o_colored_level" remove="o_cc1" separator=" "/>
```
Color issue :
![Capture d’écran 2024-08-27 à 14 43 44](https://github.com/user-attachments/assets/a9228c10-e837-416b-96a0-33627a8d9b1f)

2024-08-28 08:01 UTC, Brieuc-brd approved these changes
LGTM, good job 👍

2024-09-06 08:20 UTC, bso-odoo commented
@robodoo delegate=bvr-odoo

2024-09-19 14:30 UTC, SergeBayet commented
Commit(s) moved into
- https://github.com/odoo/design-themes/pull/919

2024-09-19 14:38 UTC, closed without merging