[IMP] theme_*: adapt themes with new `s_freegrid` snippet
odoo/design-themes pull request #881
Opened 2024-08-22 12:11 UTC by xlu-odoo

anelusia, artists, avantgarde, aviato, beauty, bewise, bistro, bookstore , buzzy, clean, cobalt, enark, graphene, kea, kiddo, loftspace, monglia, nano, notes, odoo_experts, orchid, paptic, real_estate, treehouse, vehicle, yes, zap

This commit adapts the design of `s_freegrid` for multiple themes, based on the new Odoo 18 snippet redesign.

requires: https://github.com/odoo/odoo/pull/177573

task-4104931
Part-of: task-4077427

2024-08-22 12:11 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/design-themes/pull/881.png)](https://mergebot.odoo.com/odoo/design-themes/pull/881)

2024-08-22 16:04 UTC, anso-odoo approved these changes
LGTM 👍

2024-08-28 15:44 UTC, bvr-odoo requested changes
Only a small typo, except that everything is ok

2024-08-28 15:44 UTC, bvr-odoo commented on theme_anelusia/views/snippets/s_freegrid.xml
> +    <!-- Buttont -->
typo => button

2024-08-29 14:17 UTC, bvr-odoo approved these changes

2024-08-29 14:20 UTC, bso-odoo commented
@robodoo delegate=bvr-odoo

2024-08-29 14:34 UTC, bvr-odoo commented
@robodoo r+

2024-08-29 16:34 UTC, closed without merging