[IMP] theme_anelusia, *: adapt `s_references_social`
odoo/design-themes pull request #890
Opened 2024-08-29 16:00 UTC by mano-odoo

*: theme_buzzy, theme_kea, theme_nano, theme_odoo_experts, theme_zap

Adapt the newly introduced `s_references_social` to match existing themes.

| Visual change |
|:--------:|
| Default v |
| Anelusia v |
| Buzzy v |
| Kea v |
| Nano v |
| Odoo Experts v |
| Zap v |
| ![image](https://github.com/user-attachments/assets/680554f0-b618-4764-a98f-503c9996843c) | 

task-4146797
Part-of: task-4077427

2024-08-29 16:00 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/design-themes/pull/890.png)](https://mergebot.odoo.com/odoo/design-themes/pull/890)

2024-09-06 15:02 UTC, anso-odoo requested changes
Hello @mano-odoo , some small comments 👍

2024-09-09 12:26 UTC, anso-odoo approved these changes
Only one comment but otherwise, LGTM

2024-09-09 12:26 UTC, anso-odoo commented on theme_nano/views/snippets/s_references_social.xml
> +    <!-- s_social color better contrast -->
Is it really needed ? I think the contrast is even better without 

with this change:
<img width="190" alt="Screenshot 2024-09-09 at 14 25 21" src="https://github.com/user-attachments/assets/8a1480ed-ed1a-45dd-9265-8e3b62b044d3">

default:
<img width="185" alt="Screenshot 2024-09-09 at 14 24 17" src="https://github.com/user-attachments/assets/9a4b7b3e-af84-4725-9a9e-b73b6e3b85ee">

2024-09-11 12:11 UTC, bvr-odoo approved these changes

2024-09-19 14:30 UTC, SergeBayet commented
Commit(s) moved into
- https://github.com/odoo/design-themes/pull/919

2024-09-19 14:38 UTC, closed without merging