theme_*: adapt s_references_grid to themes
odoo/design-themes pull request #891
Opened 2024-08-30 13:07 UTC by mano-odoo

* theme_anelusia, theme_buzzy, theme_kea, theme_nano, theme_odoo_experts, theme_zap

Adapt the newly introduced s_references_grid to match existing themes.

task-4146798
Part-of: task-4077427

2024-08-30 13:08 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/design-themes/pull/891.png)](https://mergebot.odoo.com/odoo/design-themes/pull/891)

2024-09-06 15:38 UTC, anso-odoo requested changes
Hey @mano-odoo, just some small issues 👍 

---

*Formatting nitpick mode ON*

Don't forget to codify ("`blabla`") the snippet title in the commit and PR title
Also if you use `theme_*` in the title,  it should be "*: anelusia, artists,..." in the message

*Formatting nitpick mode OFF*

2024-09-06 15:38 UTC, anso-odoo commented on theme_nano/views/snippets/s_references_grid.xml
Not sure about the contrast here
![Screenshot 2024-09-06 at 17 32 51](https://github.com/user-attachments/assets/11726974-02ad-4f3a-8182-c73eeef5dddd)

Also, I the logos are cut, we should increase their grid height by 1
![Screenshot 2024-09-06 at 17 35 02](https://github.com/user-attachments/assets/d3e8fd21-dc0f-4081-a4e6-b18a66ef2448)

2024-09-09 08:13 UTC, mano-odoo commented on theme_nano/views/snippets/s_references_grid.xml
As discussed visual result now: 
![image](https://github.com/user-attachments/assets/7bbc2403-3e52-4da8-beb8-cb8b10be009f)

2024-09-09 14:47 UTC, anso-odoo approved these changes

2024-09-11 13:08 UTC, bvr-odoo requested changes

2024-09-11 13:08 UTC, bvr-odoo commented on theme_zap/views/snippets/s_references_grid.xml
> +        Our <b>References</b>
Small change here: The editor cannot add `<b>` tags. It adds `<strong>` tags for bold :wink:

2024-09-12 08:24 UTC, bvr-odoo approved these changes

2024-09-19 14:31 UTC, SergeBayet commented
Commit(s) moved into
- https://github.com/odoo/design-themes/pull/919

2024-09-19 14:39 UTC, closed without merging