[IMP] theme_*: adapt `s_company_team_detail` to themes
odoo/design-themes pull request #896
Opened 2024-09-04 11:48 UTC by mano-odoo

*: theme_beauty, theme_bewise, theme_enark, theme_notes, theme_treehouse, theme_yes

This commit adapts the design themes to the new s_company_team_basic snippet.

task-4156290
Part of: task-4077427

2024-09-04 11:48 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/design-themes/pull/896.png)](https://mergebot.odoo.com/odoo/design-themes/pull/896)

2024-09-06 14:19 UTC, anso-odoo requested changes
Hey @mano-odoo small comments for you

2024-09-06 15:44 UTC, mano-odoo commented on theme_bewise/views/customizations.xml
It was missing the `o_colored_level` class 👍 
I changed the socials to text-o-color-3 for o_cc4 background 
![image](https://github.com/user-attachments/assets/9cdf3733-403b-42bc-8bb1-2adcb8594972)

2024-09-09 11:37 UTC, anso-odoo approved these changes
LGTM

2024-09-11 11:18 UTC, bvr-odoo approved these changes

2024-09-19 14:31 UTC, SergeBayet commented
Commit(s) moved into
- https://github.com/odoo/design-themes/pull/919

2024-09-19 14:38 UTC, closed without merging