[IMP] theme_anelusia, *: adapt `s_quotes_carousel_minimal` and adapt `s_quotes_carousel` first image
odoo/design-themes pull request #900
Opened 2024-09-09 12:35 UTC by Brieuc-brd

### Adapt `s_quotes_carousel` first image 
When redesigning the carousels, some adaptations were made for themes in https://github.com/odoo/design-themes/commit/f66833de41f757c65ecf660f7bbc033b6dc64d6a. This has removed an image record, which introduced a visual issue: it used an UI face image as a background.

This PR adapts the record to enhance the background image.

### Adapt `s_quotes_carousel_minimal`
This PR adapts customizations for `s_quotes_carousel_minimal`.

task-4166189
Part of task-4077427

---

Requires:
- https://github.com/odoo/odoo/pull/179648
- https://github.com/odoo/design-themes/pull/898

2024-09-09 12:35 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/design-themes/pull/900.png)](https://mergebot.odoo.com/odoo/design-themes/pull/900)

2024-09-09 14:35 UTC, chgo-odoo requested changes
Thanks @Brieuc-brd, some tiny comments but nothing technical here !

2024-09-09 14:35 UTC, chgo-odoo commented on theme_artists/views/snippets/s_quotes_carousel_minimal.xml
> +    </xpath>
As proposed on the Community PR, maybe we can remove these and make it default.

2024-09-09 14:35 UTC, chgo-odoo commented on theme_orchid/views/snippets/s_quotes_carousel_minimal.xml
> +    </xpath>
The second icon hasn't be changed here, design choice?

2024-09-09 14:35 UTC, chgo-odoo commented on theme_bookstore/views/snippets/s_quotes_carousel_minimal.xml
I'd change the job title to names, as you already did in other themes

2024-09-09 14:35 UTC, chgo-odoo commented on theme_notes/views/snippets/s_quotes_carousel_minimal.xml
Same as bookstore, I'd turn the job title into names

2024-09-19 15:35 UTC, bvr-odoo commented
Commit(s) moved into

- https://github.com/odoo/design-themes/pull/919

2024-09-19 16:59 UTC, closed without merging