[IMP] theme_real_estate: theme improvement
odoo/design-themes pull request #906
Opened 2024-09-13 06:57 UTC by anso-odoo

Revamp of `theme_real_estate`

task-4178611

2024-09-13 06:57 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/design-themes/pull/906.png)](https://mergebot.odoo.com/odoo/design-themes/pull/906)

2024-09-23 16:06 UTC, xO-Tx requested changes
@anso-odoo some adjustments needed here and it'll be ready to go :+1:

2024-09-23 16:06 UTC, xO-Tx commented on theme_real_estate/views/snippets/s_title.xml
> +        <div class="o_we_shape o_web_editor_Airy_07 o_we_animated" style="background-image: url('/web_editor/shape/web_editor/Airy/07.svg"/>
I don't think you need the `o_we_animated`  class for this shape...

2024-09-24 09:59 UTC, anso-odoo commented
Thanks @xO-Tx, fixed everything 👍

2024-09-25 08:51 UTC, qsm-odoo commented
@robodoo delegate=xO-Tx 
@xO-Tx

2024-09-25 12:06 UTC, xO-Tx commented
@robodoo r+

2024-09-25 13:00 UTC, xO-Tx commented
@robodoo r-

2024-09-25 13:33 UTC, xO-Tx commented
@robodoo r+

2024-09-25 14:05 UTC, robodoo commented
@anso-odoo @xO-Tx 'ci/runbot' failed on this reviewed PR.

2024-09-26 10:07 UTC, closed without merging