[IMP] theme_aviato: revamp the theme
odoo/design-themes pull request #923
Opened 2024-09-19 14:19 UTC by xlu-odoo

task-4178017
Part of task-4177975

2024-09-19 14:20 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/design-themes/pull/923.png)](https://mergebot.odoo.com/odoo/design-themes/pull/923)

2024-09-24 07:54 UTC, bvr-odoo requested changes

2024-09-24 07:54 UTC, bvr-odoo commented on theme_aviato/views/snippets/s_showcase.xml
> +    align-items-center
You forgot to remove this line

2024-09-24 13:16 UTC, bvr-odoo commented on theme_aviato/__manifest__.py
> +        'website.s_media_list_default_image_1': '/theme_aviato/static/src/img/content/s_wall_01.jpg',
![image](https://github.com/user-attachments/assets/66cd0eb1-5b6c-4ca8-8cbd-b5fc0b6057c9)
There are 3 times the same image on `s_media_list`.
It was already like this before this PR, but could you fix it please

2024-09-25 07:42 UTC, bso-odoo commented
@robodoo delegate=bvr-odoo

2024-09-25 12:21 UTC, bvr-odoo approved these changes

2024-09-25 12:21 UTC, bvr-odoo commented
@robodoo r+

2024-09-25 12:55 UTC, bvr-odoo commented
@robodoo r-

2024-09-25 12:57 UTC, bvr-odoo commented
@xlu-odoo needs to be rebased on 18.0 :wink:

2024-09-27 09:13 UTC, xlu-odoo commented
@bvr-odoo sorry for all notifications you must have received this morning.. Runbot is green 👍

2024-09-29 21:54 UTC, qsm-odoo commented
Being moved to https://github.com/odoo/design-themes/pull/969 (hopefully, with correct Signed-off-by)
Don't push here or there anymore, if you need to apply fixes, create a new PR to merge once the main one is merged.

2024-09-29 21:54 UTC, closed without merging