[FIX] theme_*: fix `s_big_number` wrong gradient implementation
odoo/design-themes pull request #930
Opened 2024-09-22 15:39 UTC by chgo-odoo

*: anelusia, artists, avantgarde, aviato, beauty, bewise, monglia, vehicle

This commit aims to fix a wrong implementation of gradients on the `s_big_number` snippet within the context of the web editor.

Prior to this commit, the `s_big_number` snippet was using a gradient composed of the right color, but being declared as `RGB` values.

While this is working as expected and looking like it uses the right `--o-color-*`, it's indeed working with the specific color applied in first place. If a user changes the color palette of the website, the snippet will look terrible as it doesn't adapt to the new palette.

This commit fixes the issue by using the right implementation with CSS variables.

task-4202371

2024-09-22 15:39 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/design-themes/pull/930.png)](https://mergebot.odoo.com/odoo/design-themes/pull/930)

2024-09-22 18:43 UTC, stefanorigano requested changes
Thanks @chgo-odoo .
One remark for `theme_anelusia`, ok the rest 👍

2024-09-22 18:47 UTC, chgo-odoo commented
Thanks @stefanorigano, change done !

Marked this as ready for review as the diff was only about a suggestion

2024-09-22 18:55 UTC, stefanorigano requested changes
One remark in the code.

Also, PR's description ( https://github.com/odoo/odoo/pull/180983 as well): 

- Typo: "This ~~commit~~" ->   "This pull request" 
- List linked PRs at **end** of the description, not in the middle ;)

Thanks

2024-09-22 18:55 UTC, stefanorigano commented on theme_anelusia/views/snippets/s_big_number.xml
> +        <font class="text-gradient" style="background-image: linear-gradient(15deg, var(--o-color-1) 25%,var(--o-color-5) 100%);">
Convention: missing empty character 
```suggestion
        <font class="text-gradient" style="background-image: linear-gradient(15deg, var(--o-color-1) 25%, var(--o-color-5) 100%);">
```

2024-09-23 07:09 UTC, stefanorigano approved these changes
LGTM 👍 

note: some themes untouched by this PR totally remove the 'text-gradient" effect. I'm wondering if it should be the right approach. Anyhow, adding theme back would be out of scope for this PR.. the fix it's ok 👍 

Thanks!

2025-02-13 10:27 UTC, bso-odoo commented
@robodoo delegate=bvr-odoo

2025-02-17 13:33 UTC, bvr-odoo approved these changes

2025-02-17 15:35 UTC, closed without merging