[IMP] theme_enark: revamp the theme
odoo/design-themes pull request #932
Opened 2024-09-23 13:53 UTC by Brieuc-brd

task-4178071
Part of task-4177978

| Before | After |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/bbe606b4-4fca-487c-abe7-bd1b58d4fa38) | ![enark_screenshot](https://github.com/user-attachments/assets/fda44987-06e9-447c-8fe1-2bea1db9c3f7) |

2024-09-23 13:53 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/design-themes/pull/932.png)](https://mergebot.odoo.com/odoo/design-themes/pull/932)

2024-09-24 14:46 UTC, bvr-odoo requested changes
Good work, thanks :+1: 
Just 2 small things to change

2024-09-24 14:46 UTC, bvr-odoo commented on theme_enark/static/src/js/tour.js
> +        groupName: "Columns",
not related to this line but I see a layout issue in one of the landing pages (top padding missing :wink: )
![image](https://github.com/user-attachments/assets/f531d0f4-d519-48d5-b9b1-079048cadb8b)

2024-09-24 14:46 UTC, bvr-odoo commented on theme_enark/views/snippets/s_cta_box.xml
> +        <attribute name="class" add="o_cc o_cc2 pt-0" remove="pt80" separator=" "/>
`pt-0` => `pt0`

2024-09-25 07:42 UTC, bso-odoo commented
@robodoo delegate=bvr-odoo

2024-09-25 07:54 UTC, bvr-odoo commented
@robodoo r+

2024-09-25 09:21 UTC, closed without merging