[FIX] theme_kiddo: refine the theme
odoo/design-themes pull request #947
Opened 2024-09-26 10:58 UTC by Brieuc-brd

Since the redesign of some snippets, some customizations have been broken. This commit adapts these customizations.
This commit also adjusts some spacing and font sizes.

task-4178078
Part of task-4177978

2024-09-26 10:58 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/design-themes/pull/947.png)](https://mergebot.odoo.com/odoo/design-themes/pull/947)

2024-09-26 12:45 UTC, agau-odoo requested changes
Hey :wave: Thanks for the PR :sunglasses: 

I've left some comments, but otherwise this looks very nice!

2024-09-26 12:45 UTC, agau-odoo commented on theme_kiddo/views/snippets/s_banner.xml
> +        <attribute name="data-oe-shape-data">{'shape':'web_editor/Wavy/22','flip':['x'],'showOnMobile':true,'shapeAnimationSpeed':'0'}</attribute>
There is a mismatch with the link, this one doesn't have the c3 color.

2024-09-26 12:45 UTC, agau-odoo commented on theme_kiddo/views/snippets/s_three_columns.xml
> +        <attribute name="data-oe-shape-data">{'shape':'web_editor/Origins/14_001','flip':['y'],'showOnMobile':true,'shapeAnimationSpeed':'0'}</attribute>
Same thing here, colors don't match the link

2024-09-26 15:53 UTC, Brieuc-brd commented on theme_kiddo/static/description/kiddo_screenshot.jpg
Good catch ! 🙏 I updated the screenshot 👍

2024-09-26 15:54 UTC, Brieuc-brd commented
Thanks for your review @agau-odoo 👍 
I updated the branch, could you have a look ?
The diff : https://github.com/odoo/design-themes/compare/8bb29236030d7087ed45a4421e4dd588cad15aca..d7f4e20a16bd9b0e4af893dca90ccff5e7f845bb

Thanks again !

2024-09-27 05:32 UTC, agau-odoo approved these changes
LGTM :)

@robodoo r+

2024-09-27 12:14 UTC, closed without merging