[IMP] theme_orchid: revamp theme
odoo/design-themes pull request #948
Opened 2024-09-26 11:59 UTC by stefanorigano

| `17.4` | this PR |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/c3c560cd-534a-443b-9d0d-71804d713010) | ![image](https://github.com/user-attachments/assets/b0f09f9a-6d30-4490-aa8a-b3c4983526c9) | 

task-4178087
part of task-4177975

2024-09-26 11:59 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/design-themes/pull/948.png)](https://mergebot.odoo.com/odoo/design-themes/pull/948)

2024-09-27 08:26 UTC, agau-odoo requested changes
Thanks for the PR! :)

Here are some comments, including a bunch of nitpicking:

![image](https://github.com/user-attachments/assets/9d2ce366-8dd2-49d9-ae18-747bfb714fd3)

-> this transition doesn't match the jpg preview, + it seems odd to me. It's even more apparent on bigger screens (i.e. 1440p)
The shape is cut + the white color is slightly different
The different color is also visible in the jpg preview

2024-09-27 08:26 UTC, agau-odoo commented on theme_orchid/views/snippets/s_key_images.xml
> +        <attribute name="class" add="h4-fs" remove="h1-fs"  separator=" "/>
```suggestion
        <attribute name="class" add="h4-fs" remove="h1-fs" separator=" "/>
```

2024-09-27 08:26 UTC, agau-odoo commented on theme_orchid/views/snippets/s_key_images.xml
> +        <attribute name="class" add="h4-fs" remove="h1-fs"  separator=" "/>
```suggestion
        <attribute name="class" add="h4-fs" remove="h1-fs" separator=" "/>
```

2024-09-27 08:26 UTC, agau-odoo commented on theme_orchid/views/snippets/s_key_images.xml
![image](https://github.com/user-attachments/assets/c6b31000-740f-44b8-ad6c-4aa055b78d84)
-> Image 2 has a different height, is this intended? Idk if we're supposed to handle generated images, maybe this is a bug?

2024-09-27 08:26 UTC, agau-odoo commented on theme_orchid/views/snippets/s_key_images.xml
> +        <attribute name="class" add="h4-fs" remove="h1-fs"  separator=" "/>
```suggestion
        <attribute name="class" add="h4-fs" remove="h1-fs" separator=" "/>
```

2024-09-27 08:26 UTC, agau-odoo commented on theme_orchid/views/snippets/s_key_images.xml
> +        <attribute name="class" add="h4-fs" remove="h1-fs"  separator=" "/>
```suggestion
        <attribute name="class" add="h4-fs" remove="h1-fs" separator=" "/>
```

2024-09-27 08:26 UTC, agau-odoo commented on theme_orchid/views/snippets/s_key_images.xml
> +        <attribute name="data-oe-shape-data">{'shape':'web_editor/Blobs/03', 'showOnMobile': true, 'flip': ['x','y']}</attribute>
```suggestion
        <attribute name="data-oe-shape-data">{'shape':'web_editor/Blobs/03','showOnMobile':true,'flip':['x','y']}</attribute>
```

\+ Mismatching colors with svg url below :warning:

2024-09-27 08:26 UTC, agau-odoo commented on theme_orchid/views/snippets/s_kickoff.xml
> +    <xpath expr="//span[hasclass('s_parallax_bg')]" position="replace"/>
Maybe we should add a comment to make it easier to understand that we want to remove this element, and what it is. What do you think?

2024-09-27 08:26 UTC, agau-odoo commented on theme_orchid/views/snippets/s_media_list.xml
Same thing with Image 3
![image](https://github.com/user-attachments/assets/eec7c67c-1848-4830-acd0-913c08f52d09)

2024-09-27 08:26 UTC, agau-odoo commented on theme_orchid/views/snippets/s_process_steps.xml
> +        <attribute name="class" add="o_cc5" remove="" separator=" "/>
```suggestion
        <attribute name="class" add="o_cc5" separator=" "/>
```

Nitpicking: If I'm not mistaken, and empty `remove=""` does nothing, right?

2024-09-27 08:26 UTC, agau-odoo commented on theme_orchid/views/snippets/s_references.xml
> +        <div class="o_we_shape o_web_editor_Origins_07_002" style="background-image: url('/web_editor/shape/web_editor%2FOrigins%2F07_002.svg?c3=o-color-5&amp;c4=o-color-3&amp;c5=o-color-3');"></div>
I've noticed the `o_shape_show_mobile` class gets added when I select a shape, might be worth checking on all other added/modified shapes

2024-09-27 09:02 UTC, stefanorigano commented on theme_orchid/static/src/scss/bootstrap_overridden.scss
Makes sense to me indeed. I was surprised to find the empty file.
Are we sure that we're not supposed to keep it but maybe disable it in the relative `<record>`?

Like we did for `compatibility_saas_11_4_variables_scss` 
https://github.com/odoo/design-themes/blob/18.0/theme_orchid/data/ir_asset.xml#L24

2024-09-27 09:09 UTC, qsm-odoo commented on theme_orchid/static/src/scss/bootstrap_overridden.scss
No, just remove it and it's related record :pray: 

The compatibility stuff you mention is about compatibility with saved snippet in the DOM. And TBH we will probably remove it soon too, I doubt this is used in any DB anymore :wink:

2024-09-27 09:13 UTC, stefanorigano commented on theme_orchid/static/src/scss/bootstrap_overridden.scss
Ok, I'll remove file and relative record, thanks 👍

2024-09-27 09:24 UTC, stefanorigano commented on theme_orchid/views/snippets/s_media_list.xml
Are you referring to the white image's background matching the card one?
We have "no control" on the images provided by the configurator :/

2024-09-27 09:25 UTC, stefanorigano commented on theme_orchid/views/snippets/s_key_images.xml
Unfortunately it's the undesidered but expected behavior of the "automatic image replacement" feature.

2024-09-27 09:39 UTC, agau-odoo commented on theme_orchid/views/snippets/s_media_list.xml
I meant same issue as https://github.com/odoo/design-themes/pull/948#discussion_r1778206317

What I had in mind though was maybe force the height of the image and have it display as `background-position: cover`, but that might be an issue of the base snippet

2024-09-27 10:50 UTC, stefanorigano commented on theme_orchid/views/snippets/s_media_list.xml
I think that's the default behaviour already, it uses `object-fit: cover`.
Maybe the fact that the image is predominantly white is misleading 🤔... honestly I don't see any issue here... 
| |
|--------|
| ![image](https://github.com/user-attachments/assets/d84fc382-bbb0-4550-97af-ba78936a608d) |

2024-09-27 11:30 UTC, agau-odoo commented on theme_orchid/views/snippets/s_media_list.xml
In my screenshot, the 3rd image doesn't have the same resolution, and the 3rd row has a smaller height (the 1st and the 2nd actually have a 0.9 pixel height difference too).
I think the `height: 100% !important` rule has no effect, disabling it changes nothing.
It seems to me that the image's dimensions are governed by width: 100%, which is 33% of the card width (because of parent).

If this is the intended behavior, then I'm fine with it, but if what we want is to have the same row height for the 3, then I think it might be worth investigating.

However, we probably want to deal with this on the base snippet is what I mean.

2024-09-27 12:36 UTC, stefanorigano commented on theme_orchid/views/snippets/s_media_list.xml
Yes, definitely not theme related, agreed. I'll resolve this.

2024-09-27 13:57 UTC, agau-odoo requested changes
Here are some more comments, mostly nitpicking again, but still a few important issues imo. We're almost there!

2024-09-27 13:57 UTC, agau-odoo commented on theme_orchid/static/description/theme_orchid.svg
Okay but now we get this on chromium: 
![image](https://github.com/user-attachments/assets/1618557d-1a26-4463-b2aa-2757feab06fe)

And this on firefox: 
![image](https://github.com/user-attachments/assets/9c5b62f8-af27-4ba7-b742-dab05667ae20)

I think we should prefer targeting chromium users first (biggest userbase), so if we don't have an easy fix now, let's revert to the previous version and fix this later.

The issue with the different color at the bottom part of this shape is still there 
![image](https://github.com/user-attachments/assets/90bf4c7a-e7a1-4e2c-9fbd-770abe6c43e3), but again I don't know if this is important

2024-09-27 13:57 UTC, agau-odoo commented on theme_orchid/static/description/theme_orchid.svg
There's also a weird line here (firefox): 
![image](https://github.com/user-attachments/assets/f3510e3d-4f2d-4221-b347-719c61c855b2)

2024-09-27 13:57 UTC, agau-odoo commented on theme_orchid/views/snippets/s_key_images.xml
![image](https://github.com/user-attachments/assets/e5e1d20a-6240-484a-a960-6e5bccfb6308)

The color is fixed, but the shape still clips on a 1080p screen (tested in chromium)

2024-09-27 13:57 UTC, agau-odoo commented on theme_orchid/views/snippets/s_key_images.xml
> +        <attribute name="data-oe-shape-data">{'shape':'web_editor/Blobs/03','colors':{'c2':'o-color-2'},'showOnMobile': true,'flip': ['x','y']}</attribute>
```suggestion
        <attribute name="data-oe-shape-data">{'shape':'web_editor/Blobs/03','colors':{'c2':'o-color-2'},'showOnMobile':true,'flip':['x','y']}</attribute>
```

2024-09-27 13:57 UTC, agau-odoo commented on theme_orchid/views/snippets/s_kickoff.xml
> +        <attribute name="data-oe-shape-data">{'shape':'web_editor/Origins/14_001','colors':{'c3':'o-color-3','c4':'rgba(255, 0, 0, 0)'},'showOnMobile': true}</attribute>
```suggestion
        <attribute name="data-oe-shape-data">{'shape':'web_editor/Origins/14_001','colors':{'c3':'o-color-3','c4':'rgba(255, 0, 0, 0)'},'showOnMobile':true}</attribute>
```

2024-09-27 13:57 UTC, agau-odoo commented on theme_orchid/views/snippets/s_kickoff.xml
> +    <!-- Remove the parallax effect: the background image has been alredy set in the main <section> tag -->
```suggestion
    <!-- Remove the parallax effect: the background image has been already set in the main <section> tag -->
```

2024-09-27 14:53 UTC, stefanorigano commented on theme_orchid/static/description/theme_orchid.svg
Ok, now I see. The issue it's that the font it's not loaded correctly on your side.
It should be "Elsie", see `@import` rule in the svg file.
Could you tell tell me if you get error in your console? Somehow the font it's not used and this leads to discrepancies... in my side it's good on Firefox, Chrome and Safari (OSX)

![image](https://github.com/user-attachments/assets/01288b83-317d-47a9-a379-0c75bc74b2d1)

2024-09-27 15:28 UTC, stefanorigano commented on theme_orchid/views/snippets/s_key_images.xml
> but the shape still clips on a 1080p screen (tested in chromium)

Can't be solved until we introduce responsive margin; the solution would have been to add `pt256`, but this value it's totally unsuitable for mobile.

I'll remove the shape.. I don't mind it, it's clean:

| |
|--------|
| ![image](https://github.com/user-attachments/assets/5b6baff9-0774-4a21-a7a6-a800aad2e357) |

2024-09-27 16:15 UTC, stefanorigano commented
@agau-odoo , shape removed and screenshoot/svg updated.
Nitpicking remarks addressed as well. Let me know for the font, thanks.

2024-09-29 22:22 UTC, qsm-odoo commented
Being moved to https://github.com/odoo/design-themes/pull/969 (hopefully, with correct Signed-off-by)
Don't push here or there anymore, if you need to apply fixes, create a new PR to merge once the main one is merged.

2024-09-29 22:22 UTC, closed without merging

2024-09-30 05:20 UTC, agau-odoo commented on theme_orchid/static/description/theme_orchid.svg
Oh I see! 
![image](https://github.com/user-attachments/assets/0e982764-3693-4856-8aac-903e3a8f9895)

However, obviously this works well on the runbot :woman_facepalming: sorry about that, + idk what you did but it looks centered now even if the font doesn't load, so ty :pray: