[IMP] theme_anelusia, *: adapt `s_website_form_overlay`
odoo/design-themes pull request #989
Opened 2024-10-14 13:20 UTC by Brieuc-brd

*: theme_aviato, theme_beauty, theme_bewise, theme_bistro, theme_bookstore, theme_buzzy, theme_clean, theme_cobalt, theme_enark, theme_graphene, theme_kea, theme_kiddo, theme_monglia, theme_nano, theme_notes, theme_odoo_experts, theme_orchid, theme_paptic, theme_real_estate, theme_treehouse, theme_vehicle, theme_yes, theme_zap

This commit adapts customizations for `s_website_form_overlay`.

task-4138795
Part of task-4077427

Requires:
- https://github.com/odoo/odoo/pull/183568

2024-10-14 13:20 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/design-themes/pull/989.png)](https://mergebot.odoo.com/odoo/design-themes/pull/989)

2024-10-17 13:16 UTC, mano-odoo requested changes
Thanks for your work, just a few remarks and nitpicks for you

2024-10-17 13:16 UTC, mano-odoo commented on theme_avantgarde/views/images_library.xml
> +    <field name="url">/theme_avantgarde/static/src/img/pictures/bg_image_08.jpg</field>
It appears pixellated maybe something more abstract such as `s_pricelist_boxed_default_background.jpg` ?

2024-10-17 13:16 UTC, mano-odoo commented on theme_bewise/views/image_content.xml
> +    <field name="url">/theme_bewise/static/src/img/backgrounds/college_bg.jpg</field>
Maybe another image `library_image_08` ? I don't know it's maybe ok

2024-10-18 09:00 UTC, Brieuc-brd commented on theme_aviato/views/images_library.xml
> +<!-- Website Form Overlay -->
Indeed, some themes add comments for each record, others don't. I've done this on purpose to maintain consistency with each theme.

2024-10-18 11:15 UTC, Brieuc-brd commented on theme_orchid/views/images.xml
> +    <field name="url">/theme_orchid/static/src/img/snippets/s_parallax.jpg</field>
Colors of `s_quotes_carousel_2` doesn't really match with the theme colors :/
I traded with `s_parallax.jpg`. 👍

2024-10-18 11:18 UTC, Brieuc-brd commented on theme_orchid/views/images.xml
> +    <field name="url">/theme_orchid/static/src/img/snippets/s_parallax.jpg</field>
Colors of `s_quotes_carousel_2.jpg` doesn't really match with the theme colors :/
I traded with `s_product_catalog_default_image.jpg` 👍

2024-10-18 11:19 UTC, Brieuc-brd commented
Thanks for your review @mano-odoo !
Your image suggestions are nice ! I've updated the branch, could you have a look ?
Thanks in advance !

2024-10-18 11:40 UTC, mano-odoo commented on theme_orchid/views/images.xml
> +    <field name="url">/theme_orchid/static/src/img/snippets/s_parallax.jpg</field>
Indeed looks super cool!

2024-10-18 11:42 UTC, mano-odoo approved these changes
LGTM! Thanks for updating the images 😄

2024-11-22 13:22 UTC, qsm-odoo approved these changes
@robodoo r+

2024-11-22 15:22 UTC, closed without merging